# Data Agent JPA Example Configuration
# Minimal configuration for the Data Agent JPA module

spring:
  # Database configuration (using H2 for example)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

# Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.dataagent: INFO
